"""empty message

Revision ID: ca4bd781f3d4
Revises: 3c3c4088cef9
Create Date: 2024-08-22 11:00:54.874018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4bd781f3d4'
down_revision = '3c3c4088cef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=25), nullable=False),
    sa.Column('skin_color', sa.String(length=25), nullable=False),
    sa.Column('hair_color', sa.String(length=25), nullable=False),
    sa.Column('gender', sa.String(length=25), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('character_id'),
    sa.UniqueConstraint('character_name')
    )
    op.create_table('planet',
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('planet_name', sa.String(length=25), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.Column('rotation_period', sa.Integer(), nullable=False),
    sa.Column('orbital_period', sa.Integer(), nullable=False),
    sa.Column('climate', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('planet_id'),
    sa.UniqueConstraint('planet_name')
    )
    op.create_table('vehicle',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_name', sa.String(length=25), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('load_capacity', sa.Integer(), nullable=False),
    sa.Column('armament', sa.String(length=50), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('vehicle_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    op.drop_table('planet')
    op.drop_table('character')
    # ### end Alembic commands ###
